### ISSUE TITLE
Add concepts from the Human Phenotype Ontology

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/Text-Mining-Provider-Roadmap#2]
**Please describe the concept type you would like added to the knowledge graph (KG)**
The HPO has been a frequently requested ontology to add to the concept recognition pipeline, both during the Translator Relay in April 2020 and before.

**Please provide the relevant BioLink concept**
```
phenotypic feature:
    aliases: ['sign', 'symptom', 'phenotype', 'trait', 'endophenotype']
    is_a: disease or phenotypic feature
    subclass_of: UPHENO:0001001
    class_uri: UPHENO:0001001
    mappings:
      - SIO:010056
      - WD:Q169872
    id_prefixes:
      - HP
      - EFO
      - NCIT
      - UMLS
      - MEDDRA
```

**List relevant ontologies or terminologies**
Human Phenotype Ontology
* http://obofoundry.org/ontology/hp.html
* http://purl.obolibrary.org/obo/hp.owl

**List resources of relevant gold standard annotation or available text mining tools**
* [Automatic concept recognition using the human phenotype ontology reference and test suite corpora.](https://www.ncbi.nlm.nih.gov/pubmed/25725061)
* [A new synonym-substitution method to enrich the human phenotype ontology.](https://www.ncbi.nlm.nih.gov/pubmed/29017443)
* [Integrating the human phenotype ontology into HeTOP terminology-ontology server.](https://www.ncbi.nlm.nih.gov/pubmed/23920735)
